repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0  # Última versão estável do Black
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Certifique-se de usar uma versão válida
    hooks:
      - id: isort
